stages:
- verify
- build
- test
- secret-detection
variables:
  SECRET_DETECTION_ENABLED: 'true'
include:
- template: Security/Secret-Detection.gitlab-ci.yml
cache:
  paths:
    - frontend/node_modules/
frontend_lint:
  stage: verify
  image: node:22-alpine
  script:
    - cd frontend
    - npm install
    - npm run lint

backend_check:
  stage: verify
  image: node:22-alpine
  script:
    - cd api
    - npm install
    - node --check index.js

frontend_build:
  stage: build
  image: node:22-alpine
  script:
    - cd frontend
    - npm install
    - npm run build
  artifacts:
    paths:
        - frontend/dist/
    expire_in: 1 week