name: Test
on:
  push:
    branches:
      - main

jobs:
  verify_lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'

      - name: test lint frontend
        run: npm run lint
        working-directory: frontend

      - name: test lint backend
        run: node --check index.js
        working-directory: api